name: CI
on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: 🦾 Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install -e .

      - name: 💅 Format Check
        run: make format-check

      - name: 🔎 Lint Check
        run: make lint-check

      - name: 🧪 Test
        run: make test